apiVersion: v1
kind: Service
metadata:
  name: frontend-client-service
spec:
  selector:
      app: cloudl-client
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
  
  
